`timescale 1ns/1ps
// apb_master.sv
// =============
// Turns ONE request into one APB transfer.
//
//   mem_msg_router --req--> apb_master --APB--> apb_bar --> slave
//                  <--busy--           <-------- response
//
// The request interface is the port group mem_msg_router already drives
// (valid / is_write / addr / wdata) plus ONE new signal: busy.
//
// FSM
//   M_IDLE     PSEL=0 PENABLE=0   nothing on the bus
//   M_SETUP    PSEL=1 PENABLE=0   address and control valid, exactly 1 cycle
//   M_ACCESS   PSEL=1 PENABLE=1   held until PREADY
//
// M_SETUP leaves unconditionally -- the protocol defines the setup phase as
// exactly one cycle, and a_setup_one_cycle enforces it. M_ACCESS is the only
// state whose exit the slave controls.
//
// WHY THE REGISTER FILE NOW HAS BACK-PRESSURE
// mem_msg_router used to treat the RGF as always ready:
//
//     to_rgf : dest_ready = 1'b1;     // no back-pressure
//
// A transfer occupies the bus for at least two cycles, so busy carries that
// back and the router holds the message rather than issuing a request the bus
// would drop -- the same discipline the two read controllers already get.
//
// The rate makes it free: a message is 22 us on the wire, a transfer is 20 ns
// at 100 MHz, so the bus is under 0.1% utilised and back-to-back register
// messages are impossible at any baud this design can run. The stall path
// exists to make the design correct by construction rather than correct by
// arithmetic.
//
// NO COMBINATIONAL LOOP
// busy is combinational in req_valid, and the router's dest_ready is
// combinational in busy -- but the router REGISTERS rgf_cmd_valid, so the
// loop passes through a flop. Removing the req_valid term from busy would
// break a different thing: a second strobe in the cycle right after
// acceptance would be swallowed while the FSM was still in M_SETUP.
//
// RESPONSE
// rsp_valid is one cycle, on completion. It fires for WRITES TOO -- a write
// to an unmapped aperture is worth reporting -- so a caller that only wants
// read replies qualifies with rsp_is_read.

module apb_master
    import apb_pkg::*;
(
    input  logic clk,
    input  logic rst_n,

    // ---- request in, from mem_msg_router -----------------------------
    input  logic                 req_valid,     // one-cycle strobe
    input  logic                 req_write,
    input  logic [ADDR_W-1:0]    req_addr,
    input  logic [DATA_W-1:0]    req_wdata,
    output logic                 busy,

    // ---- response out -------------------------------------------------
    output logic                 rsp_valid,     // one cycle, transfer done
    output logic                 rsp_is_read,
    output logic [DATA_W-1:0]    rsp_rdata,
    output logic                 rsp_error,     // PSLVERR captured

    // ---- APB request channel, to apb_bar ------------------------------
    // PSEL per slave is generated by the decoder. This module drives the
    // transfer-active level and the decoder qualifies it with the address.
    output logic                 m_active,
    output logic                 m_penable,
    output logic                 m_pwrite,
    output logic [ADDR_W-1:0]    m_paddr,
    output logic [DATA_W-1:0]    m_pwdata,
    output logic [STRB_W-1:0]    m_pstrb,

    // ---- APB response channel, from apb_bar ---------------------------
    input  logic                 m_pready,
    input  logic [DATA_W-1:0]    m_prdata,
    input  logic                 m_pslverr
);

    typedef enum logic [1:0] {
        M_IDLE   = 2'd0,
        M_SETUP  = 2'd1,
        M_ACCESS = 2'd2
    } state_e;

    state_e state, next_state;

    logic              write_q;
    logic [ADDR_W-1:0] addr_q;
    logic [DATA_W-1:0] wdata_q;

    // -----------------------------------------------------------------
    // Next state
    // -----------------------------------------------------------------
    always_comb begin : next_st
        next_state = state;
        unique case (state)
            M_IDLE   : if (req_valid) next_state = M_SETUP;
            M_SETUP  :                next_state = M_ACCESS;   // unconditional
            M_ACCESS : if (m_pready)  next_state = M_IDLE;
            default  :                next_state = M_IDLE;
        endcase
    end : next_st

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) state <= M_IDLE;
        else        state <= next_state;
    end

    // -----------------------------------------------------------------
    // Request capture
    //
    // Latched on acceptance so the caller need only present the request for
    // the req_valid cycle. The bus then holds address and control stable
    // across SETUP and ACCESS, which the protocol requires and which is what
    // lets the slave's read mux be combinational.
    //
    // The router already registers these, so reading them directly would save
    // 48 flops. Not done: that would make the master's protocol compliance a
    // property of whoever instantiates it rather than of the master.
    // -----------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            write_q <= 1'b0;
            addr_q  <= '0;
            wdata_q <= '0;
        end
        else if (state == M_IDLE && req_valid) begin
            write_q <= req_write;
            addr_q  <= req_addr;
            wdata_q <= req_wdata;
        end
    end

    // -----------------------------------------------------------------
    // Bus outputs
    // -----------------------------------------------------------------
    assign m_active  = (state == M_SETUP) || (state == M_ACCESS);
    assign m_penable = (state == M_ACCESS);
    assign m_pwrite  = write_q;
    assign m_paddr   = addr_q;
    assign m_pwdata  = wdata_q;

    // The RGF is word-only, so every write covers all four lanes. Driven from
    // a constant rather than left dangling so a byte-enabled slave added later
    // has a real signal to connect to.
    assign m_pstrb   = write_q ? {STRB_W{1'b1}} : {STRB_W{1'b0}};

    assign busy = (state != M_IDLE) || req_valid;

    // -----------------------------------------------------------------
    // Response
    // -----------------------------------------------------------------
    logic done;
    assign done = (state == M_ACCESS) && m_pready;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rsp_valid   <= 1'b0;
            rsp_is_read <= 1'b0;
            rsp_rdata   <= '0;
            rsp_error   <= 1'b0;
        end
        else begin
            rsp_valid   <= done;
            rsp_is_read <= done && !write_q;
            rsp_error   <= done && m_pslverr;
            if (done) rsp_rdata <= m_prdata;
        end
    end

`ifndef SYNTHESIS
    // A request issued into a busy master would be dropped on the floor --
    // exactly the silent-loss shape this design has been removing elsewhere.
    // mem_msg_router gates on busy; this catches a caller that does not.
    a_req_when_idle: assert property (
        @(posedge clk) disable iff (!rst_n)
        req_valid |-> (state == M_IDLE)
    ) else $error("%m: request issued while the master was busy");

    // SETUP is exactly one cycle. If this fires, the FSM has been edited into
    // something that is no longer APB.
    a_setup_one_cycle: assert property (
        @(posedge clk) disable iff (!rst_n)
        (state == M_SETUP) |=> (state == M_ACCESS)
    ) else $error("%m: SETUP held for more than one cycle");

    // PENABLE never asserts outside a transfer.
    a_penable_implies_active: assert property (
        @(posedge clk) disable iff (!rst_n)
        m_penable |-> m_active
    ) else $error("%m: PENABLE asserted outside a transfer");

    // Address and control stable for the whole of ACCESS, including any wait
    // states the slave inserts.
    a_addr_stable: assert property (
        @(posedge clk) disable iff (!rst_n)
        (m_active && !done) |=> ($stable(m_paddr) && $stable(m_pwrite))
    ) else $error("%m: address or control changed mid-transfer");
`endif

endmodule : apb_master
